[project]
name = "vietlot-data"
version = "0.1.0"
description = ""
authors = [
    {name = "Viet Vu", email = "vietvudanh@gmail.com"},
]
dependencies = [
    "bs4>=0.0.1",
    "pandas>=2.1.0",
    "lxml>=4.9.3",
    "attrs>=23.1.0",
    "cattrs>=23.1.2",
    "click>=8.1.7",
    "pendulum>=2.1.2",
    "requests>=2.31.0",
    "tabulate>=0.9.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
dev = ["pytest"]

