name: Crawling

on:
  push:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 1 * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11.4 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install pdm && pdm sync
      - run: bash ./bin/github_data.sh
